set nocompatible

set encoding=utf-8
scriptencoding utf-8

set hidden
set noswapfile
set incsearch
set hls
set path=.,**
set nospell
set signcolumn=no
set tabstop=2 shiftwidth=2 autoindent smartindent
set noexpandtab
set nottimeout
set ttimeoutlen=0
set ruler
set number
set noshowmode
set laststatus=2
set cursorline

highlight CursorLine term=bold cterm=bold gui=bold
highlight CursorLineNr term=bold cterm=bold gui=bold

let g:netrw_dirhistmax = 0

set wildcharm=<Tab>
set wildmenu
set wildmode=full
set wildignore+=*.bmp,*.gif,*.ico,*.jpg,*.png,*.ico
set wildignore+=*.pdf,*.psd
set wildignore+=LINCENSE,node_modules/*,.git/*

" <Tab> in normal mode shows wildmenu of buffers
nnoremap <Tab> :buffer<Space><Tab>

" Ctr-P open wildmenu for edit *
map <C-p> :e *<Tab>


syntax on

highlight LineNr ctermfg=Black cterm=bold
highlight ColorColumn ctermbg=Black


" Enable system clipboard integration
set clipboard+=unnamedplus


nnoremap <SPACE> <Nop>
let mapleader=" "


" turn terminal to normal mode with escape
"tnoremap <Esc> <C-\><C-n>

nmap <leader>N :lprev<cr>
nmap <leader>n :lnext<cr>


" move among buffers
map <leader>h :bprev<CR>
map <leader>l :bnext<CR>

map [[ :silent! eval search('{', 'b')<CR>
map ]] :silent! eval search('{')<CR>


if &term =~ '^xterm'
  " use blinking vertical bar in insert mode
  let &t_SI = "\<Esc>[5 q"
  " use solid block otherwise
  let &t_EI = "\<Esc>[2 q"
  " clear screen on vim exit
  let &t_TE = "\<Esc>[H\<Esc>[2J"
endif


hi Normal guibg=NONE ctermbg=NONE


" Plug plugins manager
" Install manager if not intalled
if empty(glob('~/.vim/autoload/plug.vim'))
	silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
		\ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

call plug#begin('~/.vim/plugged')
  Plug 'dense-analysis/ale'
	Plug 'eslint/eslint'
	Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
	Plug 'junegunn/fzf.vim'
	Plug 'pangloss/vim-javascript'
	Plug 'tomasiser/vim-code-dark'
call plug#end()

let g:codedark_conservative = 1
set background=dark
colorscheme codedark
hi Normal ctermbg=NONE
hi StatusLine ctermbg=NONE



autocmd VimEnter *
  \  if len(filter(values(g:plugs), '!isdirectory(v:val.dir)'))
  \|   PlugInstall --sync | q
  \| endif


let g:ale_fixers = {
\   '*': ['remove_trailing_lines', 'trim_whitespace'],
\   'javascript': ['eslint'],
\}
let g:ale_fix_on_save = 1

nmap <leader>j :ALENext<cr>

nnoremap <leader>ff <cmd>Files<cr>
nnoremap <leader>fg <cmd>Rg<cr>
nnoremap <leader>fb <cmd>Buffers<cr>

python3 from powerline.vim import setup as powerline_setup
python3 powerline_setup()
python3 del powerline_setup
