filetype plugin indent on

syntax on

set hidden
set noswapfile
set incsearch
set hls
set path=.,**
set spell spelllang=en_au
set number
set shiftwidth=4 tabstop=4 softtabstop=4 expandtab autoindent smartindent

highlight LineNr ctermfg=Black
highlight ColorColumn ctermbg=Black

" Enable system clipboard integration
set clipboard+=unnamedplus

" Workaround for neovim wl-clipboard and netrw interaction hang 
" (see: https://github.com/neovim/neovim/issues/6695 and
" https://github.com/neovim/neovim/issues/9806) 
let g:clipboard = {
      \   'name': 'myClipboard',
      \   'copy': {
      \      '+': 'wl-copy',
      \      '*': 'wl-copy',
      \    },
      \   'paste': {
      \      '+': 'wl-paste -o',
      \      '*': 'wl-paste -o',
      \   },
      \   'cache_enabled': 0,
      \ }

" Automatically change the current directory
autocmd BufEnter * silent! lcd %:p:h


if &term =~ '^xterm'
  let &t_SI .= "\<Esc>[4 q"
  let &t_EI .= "\<Esc>[2 q"
endif

call plug#begin('~/.vim/plugged')
  Plug 'vim-airline/vim-airline'
  Plug 'w0rp/ale'
call plug#end()


let g:airline#extensions#tabline#enabled = 1
let g:airline_powerline_fonts = 1

let g:ale_fixers = {
 \ 'javascript': ['eslint']
 \ }

let g:ale_fix_on_save = 1


nmap <silent> <c-k> :bn<cr>
nmap <silent> <c-j> :bp<cr>

tnoremap <Esc> <C-\><C-n>


